version: 0.2
env:
  variables:
    DOTNET_ROOT: /root/.dotnet
  parameter-store:
    AWS_ACCESS_KEY_ID_PARAM: /CodeBuild/AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY_PARAM: /CodeBuild/AWS_SECRET_ACCESS_KEY
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo Restore started on `date`
      - export PATH="$PATH:/root/.dotnet/tools"
      - pip install --upgrade awscli
      - aws configure set profile codebuild
      - aws configure set region  eu-west-2
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_PARAM
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_PARAM
      - echo $CODEBUILD_SRC_DIR
      - dir
      - dotnet clean  ./AWSServerless1/StepfunctionAsync.sln
      - dotnet restore ./AWSServerless1/StepfunctionAsync.sln
      - dotnet clean  ./AWSServerless1/AsyncLambda.sln
      - dotnet restore ./AWSServerless1/AsyncLambda.sln
      - cd ./AWSServerless1/OrderProcessor.Test
      - dotnet test
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet tool install -g Amazon.Lambda.Tools
      - dotnet tool update -g Amazon.Lambda.Tools
      - cd ..
      - dir
      - cd OrderOrchestration
      - dotnet lambda deploy-serverless
      
